name: Slack Auto-React (Approval & Merge)

on:
  pull_request:
    types: [closed]
  pull_request_review:
    types: [submitted]

jobs:
  trigger-slack-reaction:
  #pointer to shared logic
    uses: tractorzoom/.github/.github/workflows/shared-slack-logic.yml@main
    secrets: inherit