name: TZToast

on:
  discussion_comment:
    types: [created]
  pull_request:
    types: [closed]
  pull_request_review:
    types: [submitted]

jobs:
  trigger-slack-reaction:
    uses: tractorzoom/.github/.github/workflows/shared-toast-logic.yml@toastYML
    with:
      SLACK_CHANNEL_ID: "SLACK_CHANNEL_ID_HERE" 
    secrets: inherit