name: Add Issue to Bugs board

on:
  issues:
    types: [opened]

jobs:
  assign-issue-to-board:
    runs-on: ubuntu-latest
    steps:
      - uses: docker://takanabe/github-actions-automate-projects:v0.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.ORG_PROJECT_GITHUB_TOKEN }}
          GITHUB_PROJECT_URL: https://github.com/orgs/TractorZoom/projects/4
          GITHUB_PROJECT_COLUMN_NAME: Needs triage
